sudo: required
language: python
env:
  global:
  - secure: "I/KZwsU13eCHWLWHKrunp7JzpK+dWlPE+3t6N+E2w4lYJnjmy/ZsYnzH0/GmIOgLcmIWYeVKTmvoTpkhgw/R1DFktMmRtjV15uR8I89v/RLaPEOG7Wj+t4+ZyNyRyl2B6WqJsi4hkonPJwF18a6HxxaK5hdwtltFOXotVgcddjmrjQGpjjUArB6u+uWHIGLIfJ9k08Ty1cnCe+1IvN+9eYbENg/a0Eh7CgZVP1nbyjVNqZtXWrETeT9Q0+Fiby4EIn2/5aQ6kO/HerbZC7X5VawOnVR/rFSNeds3Y0P2HOdmJipkQaE5omVnAFj1c9LdKrrHWHf6j9tsrGwwLRnyxe5EDXt5wP0mB2o6aoiBa6q94bz9Ttb0xHjyIsYP2hIzYJCfMl+Oufi74TjwrE5Q0QGNgUX6JRN6FgwYFAYHayRWvPaMIOe3ElXPhAe+c1mVfhH9YQirQrOAIGGY5xEReVKhxGRsuM3O5yYQ41+ATAnhAb00qwCxW+hWKAj8qshLS62qvJQV1/4jm/w6UvavWKJ6XfEGOQ2l19S36ToNmVbtG0bzYr/jszpCfMuuJ35IWB3d+PSvZ5g0cYalFpuXhvPOZhZBjxS6bqqjOYDUkR+XI3ucpizKo3ENBND0P+ZhSV6rjRph2emfOZZ0LDI5G9yG6IB5hZUjG3/YfmhgTtY="
git:
  depth: false
branches:
  only:
  - master
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
pandoc_version: 2.3.1
cache:
  directories:
  - "~/Rlib"
install:
- mkdir -p ~/Rlib
- echo 'R_LIBS=~/Rlib' > .Renviron
- echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
- Rscript -e 'if(!"rmarkdown" %in% rownames(installed.packages())) { install.packages("rmarkdown",
  dependencies = TRUE) }'
- Rscript -e 'if(!"xaringan" %in% rownames(installed.packages())) { install.packages("xaringan",
  dependencies = TRUE) }'
- Rscript -e 'if(!"xaringanthemer" %in% rownames(installed.packages())) { install.packages("xaringanthemer",
  dependencies = TRUE) }'
- Rscript -e 'if(!"tinytex" %in% rownames(installed.packages())) { install.packages("tinytex",
  dependencies = TRUE) }'
- Rscript -e 'if(!"scifigure" %in% rownames(installed.packages())) { install.packages("scifigure",
  dependencies = TRUE) }'
- Rscript -e 'if(!"grid" %in% rownames(installed.packages())) { install.packages("grid",
  dependencies = TRUE) }'
- Rscript -e 'if(!"remotes" %in% rownames(installed.packages())) { install.packages("remotes",
  dependencies = TRUE) }'
- Rscript -e 'if(!"icon" %in% rownames(installed.packages())) { remotes::install_github("ropenscilabs/icon")}'
- Rscript -e 'if(!"wesanderson" %in% rownames(installed.packages())) { install.packages("wesanderson", dependencies = TRUE) }'
- Rscript -e 'tinytex::install_tinytex()'
- Rscript -e 'tinytex::tinytex_root()'
- sudo apt install python3-pip
- pip3 --version
- pip install pyyaml
before_script:
- chmod +x ./website/_build.sh
- chmod +x ./website/_deploy.sh
script:
- "./website/_build.sh"
- "./website/_deploy.sh"
