# Site settings
title: INFO550
subtitle: Data Science Toolkit
description: |
    This course is an elective for Masters and PhD students at 
    <a href='https://www.sph.emory.edu/'>Emory University Rollins School of Public Health</a>. 
    The course covers some fundamental tools used in modern (reproducible) data science. 
    Together, these tools 
    provide the ability to develop fully reproducible pipelines for data 
    analysis. By the end of the course students will have learned the tools necessary to: 
    develop reproducible workflows collaboratively using version control based on 
    <a href='https://git-scm.com/'>git</a> and <a href='https://github.com/'>GitHub</a>, 
    execute these workflows on a local computer using command line operations, 
    <a href='https://rmarkdown.rstudio.com/'>R Markdown</a>, 
    and <a href='https://www.gnu.org/software/make/'>GNU Make</a>, 
    execute the workflows in a containerized environment using 
    <a href='https://www.docker.com/'>Docker</a>, and execute the workflow in a cloud 
    environment using <a href='https://aws.amazon.com/'>Amazon Web Services</a> 
    <a href='https://aws.amazon.com/ec2/'>EC2</a> and <a href='https://aws.amazon.com/s3/'>S3</a> services). Along the way, we will 
    cover a few other tools for data science including best coding practices, basic 
    <a href='https://www.python.org/'>python</a>, 
    software unit testing, and <a href='https://travis-ci.com/'>continuous integration services</a>. 
baseurl: "/info550" # the github directory
url: "https://benkeser.github.io/" # the base hostname & protocol for your site

# host the syllabus on google docs
# File: Publish to Web
syllabus_url: "https://docs.google.com/document/d/e/2PACX-1vTPKXf13lffq2wiZuAB11OnPJQe1pNXvPEjhxiceAk5Bs164L0wyQzmksjeotB_VjT-xf_TY-zHqimS/pub?embedded=true"
githubdir: "benkeser/info550"

# Author/user information
email: benkeser@emory.edu
twitter_username: biosbenk
github_username:  benkeser
authorurl: "https://bit.ly/rsph_benkeser"
address: |
    Emory University
    Department of Biostatistics and Bioinformatics
    1518 Clifton Rd. NE
    Atlanta, GA 30322

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
